
tabsList = [
  "Main",
  "Calendar",
  "Issues",
  "Pull Requests",
]

[modules.calendar]
  tab = "Main"
  title = "ls"
  exec = "cal"


[modules.weather]
  tab = "Main"
  title = "weather"
  exec = "curl --silent wttr.in/montreal?format=4"

[modules.date]
  tab = "Main"
  title = "list files"
  exec = "date +%c"

[settings]
