
tabsList = [
  "Home",
  "Calendar",
  "Issues",
  "Pull Requests",
]

[modules.calendar]
  tab = "Calendar"
  title = "ls"
  exec = "cal"

[modules.date]
  tab = "Home"
  title = "list files"
  exec = "date +%c"

[modules.weather]
  tab = "Home"
  title = "weather"
  exec = "curl --silent wttr.in/montreal?format=4"

[settings]
