
tabs = [
  "Home",
  "Calendar",
  "Commits",
]

[modules.calendar]
  tab = "Calendar"
  title = "Calendar"
  exec = "cal --color=always"

[modules.date]
  tab = "Home"
  title = "Date"
  exec = "date +%c"

[modules.weather]
  tab = "Home"
  title = "Weather"
  exec = "curl -s wttr.in/montreal?format=4"

[modules.git]
  tab = "Commits"
  title = "commits"
  exec = "git log --oneline --color"

[settings]
